#!/bin/bash
#SBATCH --job-name=deg_bams
#SBATCH -A beagle
#SBATCH -N 1
#SBATCH -n 64
#SBATCH -t 14-00:00:00
#SBATCH --mail-type=END,FAIL
#SBATCH --mail-user=lee3617@purdue.edu
#SBATCH --output slurm-%x-%J.out

module purge
module load biocontainers
module load samtools


cd ../data
samtools view -bh -L rnaspades_degs_transcriptome.fasta.bed kw001.sorted.bam > kw001.deg.bam
samtools view -bh -L rnaspades_degs_transcriptome.fasta.bed kw002.sorted.bam > kw002.deg.bam
samtools view -bh -L rnaspades_degs_transcriptome.fasta.bed kw003.sorted.bam > kw003.deg.bam
samtools view -bh -L rnaspades_degs_transcriptome.fasta.bed kw004.sorted.bam > kw004.deg.bam
samtools view -bh -L rnaspades_degs_transcriptome.fasta.bed kw005.sorted.bam > kw005.deg.bam
samtools view -bh -L rnaspades_degs_transcriptome.fasta.bed kw006.sorted.bam > kw006.deg.bam
samtools view -bh -L rnaspades_degs_transcriptome.fasta.bed kw007.sorted.bam > kw007.deg.bam
samtools view -bh -L rnaspades_degs_transcriptome.fasta.bed kw008.sorted.bam > kw008.deg.bam
samtools view -bh -L rnaspades_degs_transcriptome.fasta.bed kw009.sorted.bam > kw009.deg.bam
samtools view -bh -L rnaspades_degs_transcriptome.fasta.bed kw010.sorted.bam > kw010.deg.bam
samtools view -bh -L rnaspades_degs_transcriptome.fasta.bed kw011.sorted.bam > kw011.deg.bam
samtools view -bh -L rnaspades_degs_transcriptome.fasta.bed kw012.sorted.bam > kw012.deg.bam
samtools view -bh -L rnaspades_degs_transcriptome.fasta.bed kw013.sorted.bam > kw013.deg.bam
samtools view -bh -L rnaspades_degs_transcriptome.fasta.bed kw014.sorted.bam > kw014.deg.bam
samtools view -bh -L rnaspades_degs_transcriptome.fasta.bed kw015.sorted.bam > kw015.deg.bam
samtools view -bh -L rnaspades_degs_transcriptome.fasta.bed kw016.sorted.bam > kw016.deg.bam
samtools view -bh -L rnaspades_degs_transcriptome.fasta.bed kw017.sorted.bam > kw017.deg.bam
samtools view -bh -L rnaspades_degs_transcriptome.fasta.bed kw018.sorted.bam > kw018.deg.bam
samtools view -bh -L rnaspades_degs_transcriptome.fasta.bed kw019.sorted.bam > kw019.deg.bam
samtools view -bh -L rnaspades_degs_transcriptome.fasta.bed kw020.sorted.bam > kw020.deg.bam
samtools view -bh -L rnaspades_degs_transcriptome.fasta.bed kw021.sorted.bam > kw021.deg.bam
samtools view -bh -L rnaspades_degs_transcriptome.fasta.bed kw022.sorted.bam > kw022.deg.bam
samtools view -bh -L rnaspades_degs_transcriptome.fasta.bed kw023.sorted.bam > kw023.deg.bam
samtools view -bh -L rnaspades_degs_transcriptome.fasta.bed kw024.sorted.bam > kw024.deg.bam
samtools view -bh -L rnaspades_degs_transcriptome.fasta.bed kw025.sorted.bam > kw025.deg.bam
samtools view -bh -L rnaspades_degs_transcriptome.fasta.bed kw026.sorted.bam > kw026.deg.bam
samtools view -bh -L rnaspades_degs_transcriptome.fasta.bed kw027.sorted.bam > kw027.deg.bam
samtools view -bh -L rnaspades_degs_transcriptome.fasta.bed kw028.sorted.bam > kw028.deg.bam
samtools view -bh -L rnaspades_degs_transcriptome.fasta.bed kw029.sorted.bam > kw029.deg.bam
samtools view -bh -L rnaspades_degs_transcriptome.fasta.bed kw030.sorted.bam > kw030.deg.bam
samtools view -bh -L rnaspades_degs_transcriptome.fasta.bed kw031.sorted.bam > kw031.deg.bam
samtools view -bh -L rnaspades_degs_transcriptome.fasta.bed kw032.sorted.bam > kw032.deg.bam
samtools view -bh -L rnaspades_degs_transcriptome.fasta.bed kw033.sorted.bam > kw033.deg.bam
samtools view -bh -L rnaspades_degs_transcriptome.fasta.bed kw034.sorted.bam > kw034.deg.bam
samtools view -bh -L rnaspades_degs_transcriptome.fasta.bed kw035.sorted.bam > kw035.deg.bam
samtools view -bh -L rnaspades_degs_transcriptome.fasta.bed kw036.sorted.bam > kw036.deg.bam
samtools view -bh -L rnaspades_degs_transcriptome.fasta.bed kw037.sorted.bam > kw037.deg.bam
samtools view -bh -L rnaspades_degs_transcriptome.fasta.bed kw038.sorted.bam > kw038.deg.bam
samtools view -bh -L rnaspades_degs_transcriptome.fasta.bed kw039.sorted.bam > kw039.deg.bam
samtools view -bh -L rnaspades_degs_transcriptome.fasta.bed kw040.sorted.bam > kw040.deg.bam
samtools view -bh -L rnaspades_degs_transcriptome.fasta.bed kw041.sorted.bam > kw041.deg.bam
samtools view -bh -L rnaspades_degs_transcriptome.fasta.bed kw042.sorted.bam > kw042.deg.bam
samtools view -bh -L rnaspades_degs_transcriptome.fasta.bed kw043.sorted.bam > kw043.deg.bam
samtools view -bh -L rnaspades_degs_transcriptome.fasta.bed kw044.sorted.bam > kw044.deg.bam
samtools view -bh -L rnaspades_degs_transcriptome.fasta.bed kw045.sorted.bam > kw045.deg.bam
samtools view -bh -L rnaspades_degs_transcriptome.fasta.bed kw046.sorted.bam > kw046.deg.bam
samtools view -bh -L rnaspades_degs_transcriptome.fasta.bed kw047.sorted.bam > kw047.deg.bam
samtools view -bh -L rnaspades_degs_transcriptome.fasta.bed kw048.sorted.bam > kw048.deg.bam
samtools view -bh -L rnaspades_degs_transcriptome.fasta.bed kw049.sorted.bam > kw049.deg.bam
samtools view -bh -L rnaspades_degs_transcriptome.fasta.bed kw050.sorted.bam > kw050.deg.bam
samtools view -bh -L rnaspades_degs_transcriptome.fasta.bed kw051.sorted.bam > kw051.deg.bam
samtools view -bh -L rnaspades_degs_transcriptome.fasta.bed kw052.sorted.bam > kw052.deg.bam
samtools view -bh -L rnaspades_degs_transcriptome.fasta.bed kw053.sorted.bam > kw053.deg.bam
samtools view -bh -L rnaspades_degs_transcriptome.fasta.bed kw054.sorted.bam > kw054.deg.bam
samtools view -bh -L rnaspades_degs_transcriptome.fasta.bed kw055.sorted.bam > kw055.deg.bam
samtools view -bh -L rnaspades_degs_transcriptome.fasta.bed kw056.sorted.bam > kw056.deg.bam
samtools view -bh -L rnaspades_degs_transcriptome.fasta.bed kw057.sorted.bam > kw057.deg.bam
samtools view -bh -L rnaspades_degs_transcriptome.fasta.bed kw058.sorted.bam > kw058.deg.bam
samtools view -bh -L rnaspades_degs_transcriptome.fasta.bed kw059.sorted.bam > kw059.deg.bam
samtools view -bh -L rnaspades_degs_transcriptome.fasta.bed kw060.sorted.bam > kw060.deg.bam
samtools view -bh -L rnaspades_degs_transcriptome.fasta.bed kw061.sorted.bam > kw061.deg.bam
samtools view -bh -L rnaspades_degs_transcriptome.fasta.bed kw062.sorted.bam > kw062.deg.bam
samtools view -bh -L rnaspades_degs_transcriptome.fasta.bed kw063.sorted.bam > kw063.deg.bam
samtools view -bh -L rnaspades_degs_transcriptome.fasta.bed kw064.sorted.bam > kw064.deg.bam
samtools view -bh -L rnaspades_degs_transcriptome.fasta.bed kw065.sorted.bam > kw065.deg.bam
samtools view -bh -L rnaspades_degs_transcriptome.fasta.bed kw066.sorted.bam > kw066.deg.bam
samtools view -bh -L rnaspades_degs_transcriptome.fasta.bed kw067.sorted.bam > kw067.deg.bam
samtools view -bh -L rnaspades_degs_transcriptome.fasta.bed kw068.sorted.bam > kw068.deg.bam
samtools view -bh -L rnaspades_degs_transcriptome.fasta.bed kw069.sorted.bam > kw069.deg.bam
samtools view -bh -L rnaspades_degs_transcriptome.fasta.bed kw070.sorted.bam > kw070.deg.bam
