#!/bin/bash

#SBATCH --job-name=GDBImport_split
#SBATCH -A beagle 
#SBATCH -t 4:00:00
#SBATCH -N 1
#SBATCH -n 60
#SBATCH --mail-type=END,FAIL
#SBATCH --mail-user=lee3617@purdue.edu
#SBATCH --output slurm-%x-%A_%a.out

module purge
module load biocontainers
module load gatk4/4.2.5.0

PROJHOME=/scratch/bell/lee3617/kellets_whelks_rnaseq/05_gatk/rnaspades_annotated_allsamples

# arrayFileFull=$(find /scratch/bell/lee3617/kellets_whelks_rnaseq/05_gatk/reference/rnaspades_annotated_split/split10_10 -name '*.bed' -print | sort | sed -n "$SLURM_ARRAY_TASK_ID"p) arrayFile=$(basename "/$arrayFileFull")
# arrayFilePre=$(basename "$arrayFile" .bed)

tmp_dir=$(mktemp -d /scratch/bell/lee3617/tmp_db/genomicsDBImport.tmp.XXXXX)

cd /scratch/bell/lee3617/kellets_whelks_rnaseq/05_gatk/rnaspades_annotated/data/04_haplotypeCaller

gatk --java-options "-Xmx64g -Xms64g" GenomicsDBImport  \
        --genomicsdb-workspace-path $PROJHOME/rnaspades_split_dbs/${arrayFilePre}_db \
        -L /scratch/bell/lee3617/kellets_whelks_rnaseq/05_gatk/reference/rnaspades_annotated_swissprot_nr.fasta.fai.bed \
        --tmp-dir $tmp_dir \
	--merge-input-intervals \
        --variant kw007_haplotypeCaller.g.vcf.gz \
        --variant kw008_haplotypeCaller.g.vcf.gz \
        --variant kw009_haplotypeCaller.g.vcf.gz \
        --variant kw010_haplotypeCaller.g.vcf.gz \
        --variant kw011_haplotypeCaller.g.vcf.gz \
        --variant kw012_haplotypeCaller.g.vcf.gz \
        --variant kw013_haplotypeCaller.g.vcf.gz \
        --variant kw014_haplotypeCaller.g.vcf.gz \
        --variant kw015_haplotypeCaller.g.vcf.gz \
        --variant kw016_haplotypeCaller.g.vcf.gz \
        --variant kw017_haplotypeCaller.g.vcf.gz \
        --variant kw018_haplotypeCaller.g.vcf.gz \
        --variant kw019_haplotypeCaller.g.vcf.gz \
        --variant kw020_haplotypeCaller.g.vcf.gz \
        --variant kw021_haplotypeCaller.g.vcf.gz \
        --variant kw022_haplotypeCaller.g.vcf.gz \
        --variant kw023_haplotypeCaller.g.vcf.gz \
        --variant kw024_haplotypeCaller.g.vcf.gz \
        --variant kw025_haplotypeCaller.g.vcf.gz \
        --variant kw026_haplotypeCaller.g.vcf.gz \
        --variant kw027_haplotypeCaller.g.vcf.gz \
        --variant kw028_haplotypeCaller.g.vcf.gz \
        --variant kw029_haplotypeCaller.g.vcf.gz \
        --variant kw030_haplotypeCaller.g.vcf.gz \
        --variant kw041_haplotypeCaller.g.vcf.gz \
        --variant kw042_haplotypeCaller.g.vcf.gz \
        --variant kw043_haplotypeCaller.g.vcf.gz \
        --variant kw044_haplotypeCaller.g.vcf.gz \
        --variant kw045_haplotypeCaller.g.vcf.gz \
        --variant kw046_haplotypeCaller.g.vcf.gz \
        --variant kw047_haplotypeCaller.g.vcf.gz \
        --variant kw048_haplotypeCaller.g.vcf.gz \
        --variant kw049_haplotypeCaller.g.vcf.gz \
        --variant kw050_haplotypeCaller.g.vcf.gz \
        --variant kw051_haplotypeCaller.g.vcf.gz \
        --variant kw052_haplotypeCaller.g.vcf.gz \
        --variant kw053_haplotypeCaller.g.vcf.gz \
        --variant kw054_haplotypeCaller.g.vcf.gz \
        --variant kw055_haplotypeCaller.g.vcf.gz \
        --variant kw056_haplotypeCaller.g.vcf.gz \
        --variant kw057_haplotypeCaller.g.vcf.gz \
        --variant kw058_haplotypeCaller.g.vcf.gz \
        --variant kw059_haplotypeCaller.g.vcf.gz \
        --variant kw060_haplotypeCaller.g.vcf.gz \
        --variant kw061_haplotypeCaller.g.vcf.gz \
        --variant kw062_haplotypeCaller.g.vcf.gz \
        --variant kw063_haplotypeCaller.g.vcf.gz \
        --variant kw064_haplotypeCaller.g.vcf.gz \
        --variant kw065_haplotypeCaller.g.vcf.gz \
        --variant kw066_haplotypeCaller.g.vcf.gz \
        --variant kw067_haplotypeCaller.g.vcf.gz \
        --variant kw068_haplotypeCaller.g.vcf.gz \
        --variant kw069_haplotypeCaller.g.vcf.gz \
        --variant kw070_haplotypeCaller.g.vcf.gz \

rm -r $tmp_dir
