#!/bin/bash
#SBATCH --job-name=fgrep
#SBATCH -A beagle
#SBATCH -N 1
#SBATCH -n 10
#SBATCH -t 14-00:00:00
#SBATCH --mail-type=END,FAIL
#SBATCH --mail-user=lee3617@purdue.edu
#SBATCH --output slurm-%x-%J.out

cd $SLURM_SUBMIT_DIR
module purge

# get all degs

tail -2770 degs_padj05.MON.NAP.csv | cut -d ',' -f8 | sed -e 's/^"//' -e 's/"$//'  > rnaspades_degs_contignames.txt
fgrep -f rnaspades_degs_contignames.txt --no-group-separator tophits.txt > alldegs_hits.txt
cat alldegs_hits.txt | cut -f3 | cut -d '|' -f2 | sort | uniq > alldegs_unique_sseqid.txt


# get up-regulated genes 
tail -2770 degs_padj05.MON.NAP.csv | cut -d ',' -f3,8 | sort -t, -k 1,1 -nr | head -1773 | cut -d ',' -f2 | sed -e 's/^"//' -e 's/"$//' > upreg_contignames.txt 
fgrep -f upreg_contignames.txt --no-group-separator tophits.txt > upreg_hits.txt 
cat upreg_hits.txt	| cut -f3 | cut -d '|' -f2 | sort | uniq > upreg_sseqid.txt 


# get down-regulated genes 
tail -2770 degs_padj05.MON.NAP.csv | cut -d ',' -f3,8 | sort -t, -k 1,1 -nr | tail -997 | cut -d ',' -f2 | sed -e 's/^"//' -e 's/"$//' > downreg_contignames.txt 
fgrep -f downreg_contignames.txt  --no-group-separator tophits.txt > downreg_hits.txt 
cat downreg_hits.txt	| cut -f3 | cut -d '|' -f2 | sort | uniq > downreg_sseqid.txt 