#!/bin/bash

#SBATCH --job-name=1_build_index
#SBATCH -A beagle
#SBATCH -N 1
#SBATCH -n 20
#SBATCH -t 60:00:00
#SBATCH --mail-type=END,FAIL
#SBATCH --mail-user=lee3617@purdue.edu

cd $SLURM_SUBMIT_DIR # set this if not using sed in Makefile
module load biocontainers
module load bowtie2/2.4.2-py38

bowtie2-build -f /scratch/bell/lee3617/kw/3_deg_pipeline/transcriptome/rnaspades_assembly_calpoly.fasta /scratch/bell/lee3617/kw/3_deg_pipeline/index/bowtie2_index/calpoly_rnaspades_index
