#!/bin/bash

#SBATCH --job-name=2_rnaspadesannot_bowtie2
#SBATCH -A standby
#SBATCH -N 1
#SBATCH -n 20
#SBATCH -t 4:00:00
#SBATCH --exclusive
#SBATCH --mail-type=END,FAIL
#SBATCH --mail-user=lee3617@purdue.edu
#SBATCH --output slurm-%J-%x.out

cd $SLURM_SUBMIT_DIR # set this if not using sed in Makefile
module load biocontainers
module load bowtie2/2.4.2-py38
bowtie2 --time --threads 20 --very-sensitive \
 -S /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/data/kw001.sam \
 -x /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/index/annotated_rnaspades_index \
 -1 /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/data/kw001_1.fq.gz \
 -2 /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/data/kw001_2.fq.gz \

bowtie2 --time --threads 20 --very-sensitive \
 -S /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/data/kw002.sam \
 -x /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/index/annotated_rnaspades_index \
 -1 /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/data/kw002_1.fq.gz \
 -2 /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/data/kw002_2.fq.gz \

bowtie2 --time --threads 20 --very-sensitive \
 -S /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/data/kw003.sam \
 -x /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/index/annotated_rnaspades_index \
 -1 /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/data/kw003_1.fq.gz \
 -2 /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/data/kw003_2.fq.gz \

bowtie2 --time --threads 20 --very-sensitive \
 -S /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/data/kw004.sam \
 -x /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/index/annotated_rnaspades_index \
 -1 /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/data/kw004_1.fq.gz \
 -2 /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/data/kw004_2.fq.gz \

bowtie2 --time --threads 20 --very-sensitive \
 -S /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/data/kw005.sam \
 -x /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/index/annotated_rnaspades_index \
 -1 /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/data/kw005_1.fq.gz \
 -2 /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/data/kw005_2.fq.gz \

bowtie2 --time --threads 20 --very-sensitive \
 -S /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/data/kw006.sam \
 -x /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/index/annotated_rnaspades_index \
 -1 /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/data/kw006_1.fq.gz \
 -2 /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/data/kw006_2.fq.gz \

bowtie2 --time --threads 20 --very-sensitive \
 -S /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/data/kw007.sam \
 -x /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/index/annotated_rnaspades_index \
 -1 /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/data/kw007_1.fq.gz \
 -2 /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/data/kw007_2.fq.gz \

bowtie2 --time --threads 20 --very-sensitive \
 -S /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/data/kw008.sam \
 -x /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/index/annotated_rnaspades_index \
 -1 /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/data/kw008_1.fq.gz \
 -2 /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/data/kw008_2.fq.gz \

bowtie2 --time --threads 20 --very-sensitive \
 -S /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/data/kw009.sam \
 -x /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/index/annotated_rnaspades_index \
 -1 /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/data/kw009_1.fq.gz \
 -2 /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/data/kw009_2.fq.gz \

bowtie2 --time --threads 20 --very-sensitive \
 -S /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/data/kw010.sam \
 -x /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/index/annotated_rnaspades_index \
 -1 /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/data/kw010_1.fq.gz \
 -2 /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/data/kw010_2.fq.gz \

bowtie2 --time --threads 20 --very-sensitive \
 -S /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/data/kw011.sam \
 -x /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/index/annotated_rnaspades_index \
 -1 /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/data/kw011_1.fq.gz \
 -2 /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/data/kw011_2.fq.gz \

bowtie2 --time --threads 20 --very-sensitive \
 -S /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/data/kw012.sam \
 -x /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/index/annotated_rnaspades_index \
 -1 /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/data/kw012_1.fq.gz \
 -2 /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/data/kw012_2.fq.gz \

bowtie2 --time --threads 20 --very-sensitive \
 -S /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/data/kw013.sam \
 -x /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/index/annotated_rnaspades_index \
 -1 /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/data/kw013_1.fq.gz \
 -2 /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/data/kw013_2.fq.gz \

bowtie2 --time --threads 20 --very-sensitive \
 -S /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/data/kw014.sam \
 -x /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/index/annotated_rnaspades_index \
 -1 /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/data/kw014_1.fq.gz \
 -2 /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/data/kw014_2.fq.gz \

bowtie2 --time --threads 20 --very-sensitive \
 -S /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/data/kw015.sam \
 -x /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/index/annotated_rnaspades_index \
 -1 /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/data/kw015_1.fq.gz \
 -2 /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/data/kw015_2.fq.gz \

bowtie2 --time --threads 20 --very-sensitive \
 -S /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/data/kw016.sam \
 -x /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/index/annotated_rnaspades_index \
 -1 /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/data/kw016_1.fq.gz \
 -2 /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/data/kw016_2.fq.gz \

bowtie2 --time --threads 20 --very-sensitive \
 -S /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/data/kw017.sam \
 -x /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/index/annotated_rnaspades_index \
 -1 /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/data/kw017_1.fq.gz \
 -2 /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/data/kw017_2.fq.gz \

bowtie2 --time --threads 20 --very-sensitive \
 -S /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/data/kw018.sam \
 -x /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/index/annotated_rnaspades_index \
 -1 /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/data/kw018_1.fq.gz \
 -2 /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/data/kw018_2.fq.gz \

bowtie2 --time --threads 20 --very-sensitive \
 -S /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/data/kw019.sam \
 -x /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/index/annotated_rnaspades_index \
 -1 /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/data/kw019_1.fq.gz \
 -2 /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/data/kw019_2.fq.gz \

bowtie2 --time --threads 20 --very-sensitive \
 -S /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/data/kw020.sam \
 -x /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/index/annotated_rnaspades_index \
 -1 /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/data/kw020_1.fq.gz \
 -2 /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/data/kw020_2.fq.gz \

bowtie2 --time --threads 20 --very-sensitive \
 -S /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/data/kw021.sam \
 -x /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/index/annotated_rnaspades_index \
 -1 /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/data/kw021_1.fq.gz \
 -2 /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/data/kw021_2.fq.gz \

bowtie2 --time --threads 20 --very-sensitive \
 -S /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/data/kw022.sam \
 -x /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/index/annotated_rnaspades_index \
 -1 /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/data/kw022_1.fq.gz \
 -2 /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/data/kw022_2.fq.gz \

bowtie2 --time --threads 20 --very-sensitive \
 -S /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/data/kw023.sam \
 -x /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/index/annotated_rnaspades_index \
 -1 /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/data/kw023_1.fq.gz \
 -2 /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/data/kw023_2.fq.gz \

bowtie2 --time --threads 20 --very-sensitive \
 -S /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/data/kw024.sam \
 -x /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/index/annotated_rnaspades_index \
 -1 /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/data/kw024_1.fq.gz \
 -2 /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/data/kw024_2.fq.gz \

bowtie2 --time --threads 20 --very-sensitive \
 -S /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/data/kw025.sam \
 -x /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/index/annotated_rnaspades_index \
 -1 /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/data/kw025_1.fq.gz \
 -2 /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/data/kw025_2.fq.gz \

bowtie2 --time --threads 20 --very-sensitive \
 -S /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/data/kw026.sam \
 -x /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/index/annotated_rnaspades_index \
 -1 /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/data/kw026_1.fq.gz \
 -2 /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/data/kw026_2.fq.gz \

bowtie2 --time --threads 20 --very-sensitive \
 -S /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/data/kw027.sam \
 -x /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/index/annotated_rnaspades_index \
 -1 /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/data/kw027_1.fq.gz \
 -2 /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/data/kw027_2.fq.gz \

bowtie2 --time --threads 20 --very-sensitive \
 -S /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/data/kw028.sam \
 -x /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/index/annotated_rnaspades_index \
 -1 /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/data/kw028_1.fq.gz \
 -2 /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/data/kw028_2.fq.gz \

bowtie2 --time --threads 20 --very-sensitive \
 -S /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/data/kw029.sam \
 -x /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/index/annotated_rnaspades_index \
 -1 /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/data/kw029_1.fq.gz \
 -2 /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/data/kw029_2.fq.gz \

bowtie2 --time --threads 20 --very-sensitive \
 -S /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/data/kw030.sam \
 -x /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/index/annotated_rnaspades_index \
 -1 /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/data/kw030_1.fq.gz \
 -2 /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/data/kw030_2.fq.gz \

bowtie2 --time --threads 20 --very-sensitive \
 -S /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/data/kw031.sam \
 -x /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/index/annotated_rnaspades_index \
 -1 /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/data/kw031_1.fq.gz \
 -2 /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/data/kw031_2.fq.gz \

bowtie2 --time --threads 20 --very-sensitive \
 -S /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/data/kw032.sam \
 -x /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/index/annotated_rnaspades_index \
 -1 /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/data/kw032_1.fq.gz \
 -2 /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/data/kw032_2.fq.gz \

bowtie2 --time --threads 20 --very-sensitive \
 -S /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/data/kw033.sam \
 -x /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/index/annotated_rnaspades_index \
 -1 /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/data/kw033_1.fq.gz \
 -2 /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/data/kw033_2.fq.gz \

bowtie2 --time --threads 20 --very-sensitive \
 -S /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/data/kw034.sam \
 -x /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/index/annotated_rnaspades_index \
 -1 /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/data/kw034_1.fq.gz \
 -2 /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/data/kw034_2.fq.gz \

bowtie2 --time --threads 20 --very-sensitive \
 -S /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/data/kw035.sam \
 -x /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/index/annotated_rnaspades_index \
 -1 /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/data/kw035_1.fq.gz \
 -2 /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/data/kw035_2.fq.gz \

bowtie2 --time --threads 20 --very-sensitive \
 -S /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/data/kw036.sam \
 -x /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/index/annotated_rnaspades_index \
 -1 /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/data/kw036_1.fq.gz \
 -2 /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/data/kw036_2.fq.gz \

bowtie2 --time --threads 20 --very-sensitive \
 -S /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/data/kw037.sam \
 -x /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/index/annotated_rnaspades_index \
 -1 /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/data/kw037_1.fq.gz \
 -2 /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/data/kw037_2.fq.gz \

bowtie2 --time --threads 20 --very-sensitive \
 -S /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/data/kw038.sam \
 -x /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/index/annotated_rnaspades_index \
 -1 /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/data/kw038_1.fq.gz \
 -2 /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/data/kw038_2.fq.gz \

bowtie2 --time --threads 20 --very-sensitive \
 -S /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/data/kw039.sam \
 -x /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/index/annotated_rnaspades_index \
 -1 /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/data/kw039_1.fq.gz \
 -2 /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/data/kw039_2.fq.gz \

bowtie2 --time --threads 20 --very-sensitive \
 -S /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/data/kw040.sam \
 -x /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/index/annotated_rnaspades_index \
 -1 /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/data/kw040_1.fq.gz \
 -2 /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/data/kw040_2.fq.gz \

bowtie2 --time --threads 20 --very-sensitive \
 -S /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/data/kw041.sam \
 -x /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/index/annotated_rnaspades_index \
 -1 /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/data/kw041_1.fq.gz \
 -2 /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/data/kw041_2.fq.gz \

bowtie2 --time --threads 20 --very-sensitive \
 -S /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/data/kw042.sam \
 -x /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/index/annotated_rnaspades_index \
 -1 /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/data/kw042_1.fq.gz \
 -2 /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/data/kw042_2.fq.gz \

bowtie2 --time --threads 20 --very-sensitive \
 -S /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/data/kw043.sam \
 -x /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/index/annotated_rnaspades_index \
 -1 /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/data/kw043_1.fq.gz \
 -2 /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/data/kw043_2.fq.gz \

bowtie2 --time --threads 20 --very-sensitive \
 -S /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/data/kw044.sam \
 -x /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/index/annotated_rnaspades_index \
 -1 /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/data/kw044_1.fq.gz \
 -2 /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/data/kw044_2.fq.gz \

bowtie2 --time --threads 20 --very-sensitive \
 -S /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/data/kw045.sam \
 -x /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/index/annotated_rnaspades_index \
 -1 /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/data/kw045_1.fq.gz \
 -2 /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/data/kw045_2.fq.gz \

bowtie2 --time --threads 20 --very-sensitive \
 -S /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/data/kw046.sam \
 -x /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/index/annotated_rnaspades_index \
 -1 /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/data/kw046_1.fq.gz \
 -2 /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/data/kw046_2.fq.gz \

bowtie2 --time --threads 20 --very-sensitive \
 -S /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/data/kw047.sam \
 -x /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/index/annotated_rnaspades_index \
 -1 /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/data/kw047_1.fq.gz \
 -2 /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/data/kw047_2.fq.gz \

bowtie2 --time --threads 20 --very-sensitive \
 -S /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/data/kw048.sam \
 -x /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/index/annotated_rnaspades_index \
 -1 /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/data/kw048_1.fq.gz \
 -2 /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/data/kw048_2.fq.gz \

bowtie2 --time --threads 20 --very-sensitive \
 -S /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/data/kw049.sam \
 -x /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/index/annotated_rnaspades_index \
 -1 /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/data/kw049_1.fq.gz \
 -2 /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/data/kw049_2.fq.gz \

bowtie2 --time --threads 20 --very-sensitive \
 -S /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/data/kw050.sam \
 -x /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/index/annotated_rnaspades_index \
 -1 /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/data/kw050_1.fq.gz \
 -2 /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/data/kw050_2.fq.gz \

bowtie2 --time --threads 20 --very-sensitive \
 -S /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/data/kw051.sam \
 -x /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/index/annotated_rnaspades_index \
 -1 /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/data/kw051_1.fq.gz \
 -2 /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/data/kw051_2.fq.gz \

bowtie2 --time --threads 20 --very-sensitive \
 -S /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/data/kw052.sam \
 -x /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/index/annotated_rnaspades_index \
 -1 /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/data/kw052_1.fq.gz \
 -2 /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/data/kw052_2.fq.gz \

bowtie2 --time --threads 20 --very-sensitive \
 -S /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/data/kw053.sam \
 -x /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/index/annotated_rnaspades_index \
 -1 /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/data/kw053_1.fq.gz \
 -2 /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/data/kw053_2.fq.gz \

bowtie2 --time --threads 20 --very-sensitive \
 -S /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/data/kw054.sam \
 -x /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/index/annotated_rnaspades_index \
 -1 /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/data/kw054_1.fq.gz \
 -2 /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/data/kw054_2.fq.gz \

bowtie2 --time --threads 20 --very-sensitive \
 -S /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/data/kw055.sam \
 -x /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/index/annotated_rnaspades_index \
 -1 /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/data/kw055_1.fq.gz \
 -2 /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/data/kw055_2.fq.gz \

bowtie2 --time --threads 20 --very-sensitive \
 -S /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/data/kw056.sam \
 -x /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/index/annotated_rnaspades_index \
 -1 /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/data/kw056_1.fq.gz \
 -2 /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/data/kw056_2.fq.gz \

bowtie2 --time --threads 20 --very-sensitive \
 -S /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/data/kw057.sam \
 -x /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/index/annotated_rnaspades_index \
 -1 /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/data/kw057_1.fq.gz \
 -2 /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/data/kw057_2.fq.gz \

bowtie2 --time --threads 20 --very-sensitive \
 -S /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/data/kw058.sam \
 -x /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/index/annotated_rnaspades_index \
 -1 /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/data/kw058_1.fq.gz \
 -2 /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/data/kw058_2.fq.gz \

bowtie2 --time --threads 20 --very-sensitive \
 -S /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/data/kw059.sam \
 -x /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/index/annotated_rnaspades_index \
 -1 /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/data/kw059_1.fq.gz \
 -2 /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/data/kw059_2.fq.gz \

bowtie2 --time --threads 20 --very-sensitive \
 -S /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/data/kw060.sam \
 -x /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/index/annotated_rnaspades_index \
 -1 /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/data/kw060_1.fq.gz \
 -2 /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/data/kw060_2.fq.gz \

bowtie2 --time --threads 20 --very-sensitive \
 -S /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/data/kw061.sam \
 -x /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/index/annotated_rnaspades_index \
 -1 /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/data/kw061_1.fq.gz \
 -2 /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/data/kw061_2.fq.gz \

bowtie2 --time --threads 20 --very-sensitive \
 -S /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/data/kw062.sam \
 -x /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/index/annotated_rnaspades_index \
 -1 /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/data/kw062_1.fq.gz \
 -2 /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/data/kw062_2.fq.gz \

bowtie2 --time --threads 20 --very-sensitive \
 -S /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/data/kw063.sam \
 -x /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/index/annotated_rnaspades_index \
 -1 /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/data/kw063_1.fq.gz \
 -2 /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/data/kw063_2.fq.gz \

bowtie2 --time --threads 20 --very-sensitive \
 -S /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/data/kw064.sam \
 -x /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/index/annotated_rnaspades_index \
 -1 /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/data/kw064_1.fq.gz \
 -2 /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/data/kw064_2.fq.gz \

bowtie2 --time --threads 20 --very-sensitive \
 -S /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/data/kw065.sam \
 -x /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/index/annotated_rnaspades_index \
 -1 /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/data/kw065_1.fq.gz \
 -2 /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/data/kw065_2.fq.gz \

bowtie2 --time --threads 20 --very-sensitive \
 -S /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/data/kw066.sam \
 -x /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/index/annotated_rnaspades_index \
 -1 /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/data/kw066_1.fq.gz \
 -2 /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/data/kw066_2.fq.gz \

bowtie2 --time --threads 20 --very-sensitive \
 -S /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/data/kw067.sam \
 -x /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/index/annotated_rnaspades_index \
 -1 /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/data/kw067_1.fq.gz \
 -2 /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/data/kw067_2.fq.gz \

bowtie2 --time --threads 20 --very-sensitive \
 -S /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/data/kw068.sam \
 -x /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/index/annotated_rnaspades_index \
 -1 /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/data/kw068_1.fq.gz \
 -2 /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/data/kw068_2.fq.gz \

bowtie2 --time --threads 20 --very-sensitive \
 -S /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/data/kw069.sam \
 -x /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/index/annotated_rnaspades_index \
 -1 /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/data/kw069_1.fq.gz \
 -2 /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/data/kw069_2.fq.gz \

bowtie2 --time --threads 20 --very-sensitive \
 -S /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/data/kw070.sam \
 -x /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/index/annotated_rnaspades_index \
 -1 /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/data/kw070_1.fq.gz \
 -2 /scratch/bell/lee3617/kellets_whelks_rnaseq/04_deg_pipeline/data/kw070_2.fq.gz \

